import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "TAKASAKI TOURS",
  description: "Generated by create next app",
  appleWebApp: {
    title: "Takasaki",
  },
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
